fix: Update craco to 3.3.1 to resolve error
See https://github.com/sharegate/craco/issues/61.
Updating to craco 3.3.1 resolves error when trying to install dependencies and build:
```
Error: Cannot find module '~/code/src/paritytech/fether/node_modules/react-scripts/config/webpack.config.dev'
```