fix: Remove stage-0 and add dependencies to fix errors. Update to Babel 7.2.3
Fixes errors:

```
{ Error: Cannot find module '@babel/plugin-proposal-class-properties' from '/Users/scon/code/src/paritytech/fether/packages/fether-ui'
```

```
Failed to minify the bundle. Error: static/js/main.f19a0eac.chunk.js from Terser
TypeError: Cannot read property 'minify' of undefined
```